[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
# command = "open" # On macOS
# command = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control"

[[keyboard.bindings]]
action = "Last"
key = 5
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "Bracket"
key = 6
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "FirstOccupied"
key = 7
mode = "Vi"
mods = "Shift"
